### PR TITLE
Ava

### PR DESCRIPTION
**Pull request by GauthamN**
Please describe the purpose of this pull request below.
The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)

Copy/paste from CHANGELOG.md is good

### Added
- Config for ava tests
- Unit tests for riskmgmt, compliance, version

### Changed
- fundShares tests to ava.js
- RMMakeOrders to allow the equalto case

### Removed
- Jasmine dependancy

### CODE REVIEW

**Comment by schmidsi** [comment]
Just curious: What convinced you to use ava?

**Comment by GauthamN** [comment]
Think the concurrent running of tests. Although doesn't offer much difference in integration tests, think helps speeding up unit tests

**Comment by schmidsi** [comment]
Yes, parallelisation is a big plus for Ava. Do you know if the expectation syntax is compatible with jasmine/jest? Would be great to share and reuse some expectation across projects. It's also helpful to use similar tools along the way.

**Comment by GauthamN** [comment]
Yes, custom assertions can be used with ava. Also group testing: https://github.com/sheerun/ava-spec

**Pull request merged**
