### PR TITLE
Require contracts

### PR DESCRIPTION
**Pull request by makoto**
Hi. 

When I run the test according to your README instruction, I encountered the following 3 errors.

https://gist.github.com/makoto/8c117d741d9960a7116dcd2e4513f626

These changes should fix 2 of 3 errors. I don't think I can fix the last error as I cannot guess the correct behavior from the test and I also saw that other tests in the same test files are commented out.

Thanks.

### CODE REVIEW

**Comment by retotrinkler** [comment]
yeah nav and exchange need fixing..

**Comment by makoto** [comment]
BTW what is the responsibility of `nav.js` ? Is it more like integration test (shorten for `naviation`)?

**Comment by retotrinkler** [comment]
NAV stands for net asset value. Basically how much value all assets have together (denominated in Ether)

**Comment by retotrinkler** [comment]
ah idea of nav.js is to test investing in portfolio then trading of manager then input of new prices then recalculating nav and thus performance and finally redeeming - should simulate an entire investment - trading - redeeming circle

**Pull request merged**
